
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersbapp
  labels:
    app: usersbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersbapp
  template:
    metadata:
      labels:
        app: usersbapp
    spec:
      containers:
        - name: restaurantapp
          image: sumit30/usersb:s9
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: usersb-service
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: usersbapp
 
